language: python

addons:
  postgresql: "9.4"

services:
  - postgresql


install:
  - pip install tox

before_install:
    - pip install -r requirements.txt
    - python manage.py migrate --noinput

before_script:
  - psql -c 'create database meta_id_test;' -U postgres

# command to run tests using coverage, e.g. python setup.py test
script: make tox

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
