language: python

addons:
  postgresql: "9.4"

services:
  - postgresql


install:
  - pip install tox

before_install:
    - pip install -r requirements.txt
    - python manage.py migrate --noinput

# command to run tests using coverage, e.g. python setup.py test
script: make tox

env:
  - TOXENV=py27 DATABASE_URL="postgres://travis@localhost/travis"
  - TOXENV=py33 DATABASE_URL="postgres://travis@localhost/travis"
  - TOXENV=py34 DATABASE_URL="postgres://travis@localhost/travis"
  - TOXENV=py35 DATABASE_URL="postgres://travis@localhost/travis"
