language: python

addons:
  postgresql: "9.4"

services:
  - postgresql


install:
  - pip install tox pyenv

before_install:
    - pip install -r requirements.txt
    - python manage.py migrate --noinput

before_script:
    - sudo -u postgres createdb -O meta_id_test -p 5432

# command to run tests using coverage, e.g. python setup.py test
script: make tox

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
