language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

addons:
  postgresql: "9.4"

services:
  - postgresql

env:
  - DATABASE_URL="postgres://travis@localhost/travis"

before_install:
  #- pip install codecov
    - pip install -r requirements.txt
    - python manage.py migrate --noinput

# command to run tests using coverage, e.g. python setup.py test
script: python manage.py test --nomigrations

# after_success:
#   - codecov
